name: CIPipeline
on:[push]
jobs:
  test:
    runs-on: ubuntu-latest
  steps:
    -name:Checkout du code
     uses:actions/checkout@v2
    -name: Configure Python
     uses: actions/setup-python@v2
    with:
      python-version: '3.x'
    -name : Installer les dependances
    run : |
      pip install pytest
    -name :Executer les tests
     run: |
      pytest tests/
